name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "C:\Users\Yaelle\OneDrive\Documents\Ella_files\Learning\API_Postman\JIRA API Test2.postman_collection.json" -e "C:\Users\Yaelle\OneDrive\Documents\Ella_files\Learning\API_Postman\Gin3la JIRA Live.postman_environment.json" -d "C:\Users\Yaelle\OneDrive\Documents\Ella_files\Learning\API_Postman\test_data_jira_csv.csv"
